name: Build

on:
  push:
    branches:
      - main
      - experimental

  pull_request:
    branches:
      - main
      - experimental

  workflow_dispatch:


jobs:

  buildLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libvlc-dev libvlccore-dev

      - name: Setup Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp --quiet
          chmod +x ./setup/unix.sh
          ./setup/unix.sh

      - name: Skip SScript setup mode
        run: |
          echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa

      - name: Create Version
        run: |
          echo "${{ github.run_id }}" > VERSION

      - name: Build Linux
        run: |
          haxelib run lime build Project.xml linux \
          --app-version="4.0.0-${{ github.run_id }}" \
          -D officialBuild

      - name: Upload Linux
        uses: actions/upload-artifact@v4.3.4
        with:
          name: linuxBuild
          path: export/release/linux/bin



  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Haxelib
        shell: cmd
        run: |
          haxelib setup C:\haxelib
          haxelib install hxcpp --quiet
          call setup\windows.bat

      - name: Skip SScript setup mode
        shell: cmd
        run: |
          echo oy9:showMacroty8:loopCosti25y10:includeAllfg>>%USERPROFILE%\settings.cocoa

      - name: Create Version
        shell: cmd
        run: |
          echo ${{ github.run_id }} > VERSION

      - name: Build Windows
        shell: cmd
        run: |
          haxelib run lime build Project.xml windows ^
          --app-version="4.0.0-${{ github.run_id }}" ^
          -D officialBuild

      - name: Upload Windows
        uses: actions/upload-artifact@v4.3.4
        with:
          name: windowsBuild
          path: export/release/windows/bin



  buildMac:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Setup Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp --quiet
          chmod +x ./setup/unix.sh
          ./setup/unix.sh

      - name: Skip SScript setup mode
        run: |
          echo 'oy9:showMacroty8:loopCosti25y10:includeAllfg' >> ~/settings.cocoa

      - name: Create Version
        run: |
          echo "${{ github.run_id }}" > VERSION

      - name: Build Mac
        run: |
          haxelib run lime build Project.xml mac \
          --app-version="4.0.0-${{ github.run_id }}" \
          -D officialBuild

      - name: Upload Mac
        uses: actions/upload-artifact@v4.3.4
        with:
          name: macBuild
          path: export/release/macos/bin
